sindresorhus/awesome-electron

readme.md

Fireball is a game editor for creating mobile and  HTML5 games.
Check it out: http://fireball-x.com/en

Add Fireball to closed source list

---

readme.md

Yet another boilerplate, with yet the same name as yours @sindresorhus :)

Added electron-boilerplate

---

readme.md

It's a simple screenshot and screen recording app for Android devices. I just made it for fun. Hopefully, it's awesome enough.

Add Snapper

---

readme.md

Add screencast on multi window electron apps

---

readme.md

https://github.com/jprichardson/electron-mocha

add electron-mocha

---

readme.md

https://github.com/jprichardson/electron-ipc-stream

add electron-ipc-stream

---

readme.md

[Yeoman App](https://github.com/yeoman/yeoman-app) - A desktop app that scaffolds projects using Yeoman.

Add Yeoman App to example apps

---

readme.md

Add mojibar app

---

readme.md

I've just written an article about starting desktop application development with Electron.
It could be a good fit to this list.

Add Building a desktop application with Electron article

---

readme.md

This pull request is better than my last attempt. Thanks for fixing that one for me.
Shiba is a really sweet Markdown preview app.
https://github.com/rhysd/Shiba

Add Shiba app

---

readme.md

Add nuTorrent

---

readme.md

Add Black Screen

---

readme.md

Nightmare is an alternative to PhantomJS that is based on Electron.
Proof that it uses Electron can be found in the project [readme](https://github.com/segmentio/nightmare/blob/master/Readme.md) and in the package.json located [here](https://github.com/segmentio/nightmare/blob/master/package.json).

Add Nightmare to the Tools section

---

readme.md

Add Tèsèvè

---

readme.md

Please add our application.
For evidence, took capture of info.plist.
Best

add Typetalk

---

readme.md

I’d just like to say a huge thank you for this repo. It’s helped enormously in developing my app and I hope my repo can help someone like this has for me.

Adding Kakapo to open source

---

readme.md

An open source Tetris game built with Electron: https://github.com/kvnneff/bloxparty

add Blox Party

---

readme.md

Trendy is an open source client for [GitHub trending repositories](https://github.com/trending).
http://rhysd.github.io/Trendy/
Repository page is below:
https://github.com/rhysd/Trendy

Add Trendy app

---

readme.md

Add Pingendo app

---

readme.md

The name has been changed to Boostnote.
...Due to earlier existence of [Boost C++ Library](http://www.boost.org/)... haha...
Btw, we launched windows app today! :D

Our app name has been changed.

---

readme.md

One of the group for korean electron users

Add electron-kr

---

readme.md

> Abricotine is an open-source markdown editor built for desktop.
https://github.com/brrd/Abricotine

Add Abricotine

---

readme.md

http://a9.io/alienbox/
This is an open source reddit inbox menubar app for OS X.

Add alienbox

---

readme.md

tweet-rec is open source, tweet recording player by electron.

Add tweet-rec

---

readme.md

FatFileFinder is a great tools build with electron... :+1:

Add FatFileFinder

---

readme.md

Removes unexisting app

---

readme.md

[Simplenote](https://github.com/Automattic/simplenote-electron) is the simplest way to keep notes. Supports taking notes in markdown

Add Simplenote

---

readme.md

adds @kevinsawicki's https://github.com/kevinsawicki/spectron

add spectron

---

readme.md

This talk was given at Forward 4 Web Summit, Feb 2016 about the "Perks of
the New Desktop".
https://www.youtube.com/watch?v=jRPUB-D1Wx0
It begins with an introduction about Electron, a basic overview of how
it works, then goes on to discuss a few key benefits of this development
environment:
1. Native experiences
2. Offline & data storage
3. Modern performance tools
4. Extensibility
The talk was professionally recorded by the Forward Web Summit team and
has both slides and live demos over the course of 45 minutes.

Add Electron talk

---

readme.md

> Pristine Twitter app
https://github.com/sindresorhus/anatine

Add Anatine

---

readme.md

> Native mattermost chat client
https://github.com/mattermost/desktop

Add Mattermost

---

readme.md

- [MediumDesk](https://github.com/sivragav/mediumdesk) - Unofficial Medium app.

Add MediumDesk

---

readme.md

[Lightgallery ](https://github.com/sachinchoolur/lightgallery-desktop) - A modern, electron and nodejs based image viewer for Mac, Windows and Linux.

Add Lightgallery

---

readme.md

https://github.com/sindresorhus/electron-config

Add electron-config

---

readme.md

https://github.com/sindresorhus/electron-context-menu

Add electron-context-menu

---

readme.md

This is an update video to "Creating Desktop Apps with Electron" where the new syntax and APIs are used and explained. Thank you!

Add Getting Started with Electron 1.x video

---

readme.md

Add Automint

---

readme.md

Created a new PR. Thanks @sindresorhus :)

Add CrossCloud

---

readme.md

Toshocat helps you keep track of the anime/manga you've watched/read. Comes with a one-click installer and automatic updates through Squirrel.
https://github.com/tofuness/Toshocat :ok_hand: :frog:

Add Toshocat

---

readme.md

host: @kentcdodds
guests: @emorikawa and @jlord

add javascript air podcast

---

readme.md

I work there - we use electron. It's pretty awesome.

Add Discord

---

readme.md

I'm one of the authors of Building an Electron Edge and i feel like the book is a good introduction for starters.

Add `Building an Electron Edge` book

---

readme.md

I'm sorry, i've got my own book's name wrong :(

Fix book name

---

readme.md

Read more: https://medium.com/wire-news/you-can-now-build-your-own-wire-client-ea9ed9214e26

Wire messenger is now "Open Source"

---

readme.md

Add The Changelog episode to Podcasts section

---

readme.md

"In this episode, Adam talks to Jessica Lord of GitHub about building desktop applications in HTML and JavaScript using Electron."

Add the Full Stack Radio episode to the podcast section

---

readme.md

Thank you for `awesome-electron`.  It was a huge help in building this app.

Add Reactotron

---

readme.md

Unofficial Instagram desktop app by @terkelg

Add unofficial Instagram app

---

readme.md

From the moonview readme:
...
moonview allows you to write text files inside an ambient bubble. Pick from a collection of medias and create your own writing environment: moonview comes packaged with a handful of fonts, backdrops, field recordings, and audio stems.
...

Add Moonview

---

readme.md

Add Inkdrop

---

readme.md

Boostnote can store snippet notes also. This is the screenshot. http://b00st.io/assets/img/ui.png
(It would be thankful if you correct the description.... I'm not good at speaking English.)

Update description of Boostnote

---

readme.md

This one is like Franz which is already listed.
The main differences are:
* Can connect to more services.
* Open source.

Add Rambox

---

readme.md

Update video link to Electron 1.x.x version

---

readme.md

Add Exodus (https://www.exodus.io/) an all-in-one app to secure, manage, and trade blockchain assets to the closed source apps.

Add Exodus

---

readme.md

A material design color palette for the menubar. On macOS, linux, and windows.

Add Materialette

---

readme.md

Add electron-vibrancy

---

readme.md

This PR adds [elemon](https://github.com/mawni/elemon) link to the `Using Electron` part of the readme. `elemon` is a live-reload tool that can be used when developing applications. Thanks.

Add elemon

---

readme.md

Add electron-is-accelerator

---

readme.md

https://telegram.me/electron_ru

Add Telegram chat (Russian) to Community section

---

readme.md

Please add my app to the Awesome Electron app listing 😄
I think this app is really useful and would benefit other users (like myself) who use GroupMe and don't want to have to rely on the [webapp](https://web.groupme.com/).
Thanks!

Add GroupMe

---

readme.md

Please add my app to the Awesome Electron app listing 😄
I think this app is really useful and would benefit other users (like myself) who love GIFs (all content is from [Giffy](http://giphy.com/)) by allowing them to use them in more places than just Messenger and Slack.
Thanks!

Add GIFBar

---

readme.md

Add Stacer

---

readme.md

Add the Facebook community

---

readme.md

Nylas N1 product name

---

readme.md

Add Hackolade

---

readme.md

Module to achieve this long outstanding issue on Electron, https://github.com/electron/electron/issues/1692
https://github.com/tommoor/electron-lets-move

Add electron-lets-move

---

readme.md

Cerebro is an extensible launcher that focused on speed and good UI and UX. 
* Website: https://cerebroapp.com
* Github repo: https://github.com/KELiON/cerebro
We've already [discussed](https://github.com/sindresorhus/awesome-electron/issues/378#issuecomment-263111556) this app in #378 and after several releases I think it is ready to be added to this list.

Add Cerebro

---

readme.md

Repo: https://github.com/egoist/devdocs-app

Add DevDocs

---

readme.md

Whatsie is not available anymore. Please use the official client.

Remove Whatsie

---

readme.md

I made this simple video editor for super quickly discarding useless parts from big raw video files from video cameras/drones etc without re-encoding. It's based on Electron and React and uses ffmpeg (included) for the processing.
Reason: I released it last year and it has become quite popular and I got a lot of positive feedback from people who found it very useful. So I think it would qualify as an awesome electron app.
https://github.com/mifi/lossless-cut

Add LosslessCut

---

readme.md

Electron: Building Cross Platform Desktop Apps

Add a video course

---

readme.md

I think it should be included, because it's verry innovative web browser with lots of features. It has got Material Design UI and extensions system.
I need feedback from you, because the project is in alpha and doesn't include all features.

Add Wexond

---

readme.md

Removes DevDocs duplicate

---

readme.md

Insomnia is an application for interacting with HTTP APIs. I also officially open-sourced it this week!
**Website:** https://insomnia.rest
**GitHub:** https://github.com/getinsomnia/insomnia
Let me know if you have any questions or concerns 👋

Add Insomnia

---

readme.md

Fix broken link for Insomnia

---

readme.md

Add a link and description for ScreenSquid on the awesome-electron list.
The guidelines ask for proof that the app was made in Electron. Well @NicoSantangelo [hacked the app and ported it to linux](https://screensquid-linux.nicosantangelo.com/).

Add ScreenSquid

---

readme.md

Proof of using electron: check app size 🤦‍♂️ 
More seriously: this is the content of the package:

Add CashNotify

---

readme.md

I haven't had time to work on this, the project is dead :disappointed:

Remove SIV Image Viewer

---

readme.md

https://github.com/sindresorhus/electron-unhandled

Add electron-unhandled

---

readme.md

This PR adds _Electron in Action_ which is available in its early access edition now and is scheduled have a completed manuscript at the end of July.

Add Electron in Action

---

readme.md

I changed my username so my repo moved a bit. thanks!

Fix Snapper url

---

readme.md

👍  https://github.com/getstation/electron-process-manager

Add electron-process-manager

---

readme.md

Add electron-next-skeleton

---

readme.md

Hi, I added Mockoon in the closed source section. It's a server/REST API mocking tool I created.
Would be very glad if it could be added to the list!
Thanks :)
Website: https://mockoon.com
Medium article with some info on the tools used (Electron / Angular): https://medium.com/@255kb/introducing-mockoon-easy-to-use-api-mocking-desktop-application-e781761fcaed

Add Mockoon app

---

readme.md

https://github.com/kewde/electron-sandbox
A tutorial/boilerplate that comes with default secure settings.

Add electron-sandbox

---

readme.md

Twitch Blog Post:  https://blog.twitch.tv/introducing-the-twitch-desktop-app-beta-d941a280433
External Article: https://www.ghacks.net/2017/03/17/twitch-desktop-app-first-look/

Add Twitch

---

readme.md

Hi,
Would you be so kind as to add Cross-Platform Desktop Applications to your book list.
Thanks :)

Add "Cross-Platform Desktop Applications" book

---

readme.md

https://comma-chameleon.io/ CSV editor, built with electron, supporting data package export and octopub!

Add Comma Chameleon

---

readme.md

https://www.youtube.com/watch?v=DDjVaHPvRdM
This video contains some good talks on improving app startup time, debugging crashes, etc.

Add SF Electron meetup video

---

readme.md

Added electron-touchbar-example 
> Sample  touchbar integration

Touch Bar API sample

---

readme.md

Following #499 
Are you ok with the description?

Add `Electron on the App Store` article

---

readme.md

Add Cleaver to the list of closed source apps

---

readme.md

This PR will add Inboxer to the list of Electron apps.
**Repo:** https://github.com/denysdovhan/inboxer
**Website:** https://denysdovhan.com/inboxer
**Publication on Medium:** https://medium.com/@denysdovhan/inboxer-1-0-0-is-out-ce1521c1e5bf 
* **Don't use another company's trademarks**: Inboxer has a [Disclaimer](https://github.com/denysdovhan/inboxer#disclaimer) which let users know:
> This code is in no way affiliated with, authorised, maintained, sponsored or endorsed by Google or any of its affiliates or subsidiaries. This is an independent and unofficial Inbox by Gmail app. Use it at your own risk.
* **If you just created something, wait at least 20 days before submitting.** Yes, I waited for awhile, release few new versions and made some features.
* **Submitted open source apps …

Add Inboxer

---

readme.md

Add angular-electron

---

readme.md

https://github.com/sindresorhus/electron-reloader

Add electron-reloader

---

readme.md

Fix broken Electron In Action preview link

---

readme.md

[FreeMAN](https://github.com/matthew-matvei/freeman) is a free, extensible, cross-platform file manager for power users. It aims for a keyboard-led focus for fast navigation, with an integrated terminal for each of the dual panes.

Add FreeMAN

---

readme.md

Add Pretzel

---

readme.md

Add Brandy

---

readme.md

Cacher is a code snippet organizer for pro developers and their teams. It is a cross-platform, cloud-based app used to curate a snippet library.
Features:
* Support for editing and viewing 100+ programming languages.
* Flexible color-coded labels to categorize snippets.
* Shareable snippet pages via Cacher's code-sharing community: [snippets.cacher.io](https://snippets.cacher.io)
* Team and organization features like shared libraries, notifications, role management and code reviews.
* Desktop clients for macOS, Windows and Linux.
* Full-featured web app: [app.cacher.io](https://app.cacher.io)
**Note: This Electron app shares the same Angular-based frontend code across its macOS, Windows, Linux and Web clients.**
Screenshot of app in development with Dev Tools open:
---
**By submitting …

Add Cacher

---

readme.md

Use HTTPS for some links

---

readme.md

saves a HTTP redirect to https://sindresorhus.com/

Convert a link to HTTPS

---

readme.md

Building an Electron File Explorer with Quasar (and Vue)

Add article "Building a file explorer with Electron, Quasar, and Vue"

---

readme.md

Last April I wrote an article on how I use google analytics to collect anonymous user statistics in Electron applications that's generally useful for Electron developers.

Add article on gathering user statistics

---

readme.md

[Notable](https://github.com/fabiospampinato/notable) - The markdown-based note-taking app that doesn't suck.
I think it should be added because if its design goals resonate with you then this is probably the best note-taking app available IMHO.
Some screenshots:

Add Notable

---

readme.md

Remove ipc-flux

---

readme.md

Update angular-electron description

---

readme.md

Add electron-ssl-pinning

---

readme.md

Mini Diary is a simple and secure journal app for macOS, Windows and Linux. It features a beautiful and clean design with no distractions, letting you fully focus on your writing.
**Features:**
- Light and dark themes
- Basic text formatting (Markdown support)
- Locally encrypted
- Import from other journal apps
- Export to various formats
**Download:** https://minidiary.app

Add Mini Diary

---

readme.md

Add Unsplash Wallpapers

---

readme.md

Motrix is a download manager which has been built using Vue, VueX, Electron and Element.
It's a very good resource for understanding and learning both Vue and Electron.

Add Motrix

---

readme.md

https://github.com/frankwallis/electron-ipc-proxy
It's awesome :) thanks

Add electron-ipc-proxy

---

readme.md

Debugtron is a CLI tool to debug in-production Electron based apps.
Repo here: https://github.com/pd4d10/debugtron
Demo:

Add debugtron

---

readme.md

MusicPlus is a free music application for MacOS & Windows.
Homepage: https://musicplus.io
Email: contact@musicplus.io

Add MusicPlus

---

readme.md

Update URL for Paws

---

readme.md

Add Moon Modeler

---

readme.md

Repo here: [jest-electron](https://github.com/hustcc/jest-electron)
- run test case in electron
- `debug` mode to debug the ui with electron

Add jest-electron

---

readme.md

https://notion.so is the app I'm submitting. I did not create this, but it's a pretty widely used note taking application that people keep on hyping on twitter etc. It's listed in the official [Electron Apps](https://electronjs.org/apps/notion) page and it's semi-public information that it's built with Electron but I don't have any better sources to link to though.

Add Notion

---

readme.md

[FATpick](https://www.fatpick.com/) is a commercial application that "gamifies" guitar practice in a fashion similar to those "rock star" games that were popular on consoles a few years back, but with real instruments. Users select (or import) a song. FATpick displays the musical score as an auto-scrolling tab, synchronized with original or generated backing-tracks. FATpick evaluates the user's performance as they play along with a real guitar, scoring the performance based on timing and accuracy.
FATpick is an example of an Electron-based app with a slightly unusual UI/UX. It makes extensive use of the Web Audio API and Canvas rendering to present a complex, multimedia interface with real-time audio signal processing.
This blog post - https://www.fatpick.com/blog/tech-stack-2019 - …

Add FATpick

---

readme.md

[Upcount.app](https://www.upcount.app/) is an Invoicing application focusing on ease of use and offline-first approach. The application is fully open source & uses Electron - has an automated Github actions build process and is looking for [ideas, suggestions](https://github.com/madisvain/upcount/issues) or contributors.

Add Upcount

---

readme.md

I created [Electronmon](https://github.com/catdad/electronmon) to address some common issues with existing reloaders:
* it does not lose access to stdout/stderr on the first application reload
* it does not require changes to application code, as it functions all externally

Add electronmon

---

readme.md

Article I wrote on Electron notarization. It's also linked in the official docs, so a good resource.

Add article on Electron notarization

---

readme.md

Adding a new video of the Electron presentation I gave last November: https://www.youtube.com/watch?v=fw4PmPaghyU 
It has tips and tricks on how to make a desktop app with electron that works well on mac, windows and linux.

Add new video

---

readme.md

Add Swifty

---

readme.md

Changed my GitHub username a long time ago so just keeping the list up to date.

Update Gitify repo link

---

readme.md

https://github.com/doyensec/electronegativity
It detects many/most of the issues on the Electron security checklist - https://www.electronjs.org/docs/tutorial/security

Add electronegativity

---

readme.md

Please consider including Taskade. Thank you!
Here is our app listed on ElectronJS https://www.electronjs.org/apps/taskade

Add Taskade

---

readme.md

Update a boilerplate description

---

readme.md

Hi Sindre!
We built Mouseless & Glyphfinder, both (technically speaking) pretty similar apps, hence I created only one PR. Unfortunately there is no blog article or anything that explains the technology behind those apps (we should probably write one). If you want to give them a try, send me a DM on Twitter (https://twitter.com/hanspagel), I’ll send you a license for free.
If you think they don’t belong in the list, feel free to close the PR. No bad vibes. Keep up the good work!
Bests,
Hans

Add Glyphfinder and Mouseless

---

readme.md

Add LightProxy

---

readme.md

Beekeeper Studio - Open Source SQL Editor and DB Manager. ~1.3k stars
beekeeperstudio.io

Add Beekeeper Studio

---

readme.md

We @doyensec put together an awesome list covering @electronjs security, with presentations,
bug write-ups, and all kinds of content to help developers and security folks on their Electron security testing. 
https://github.com/doyensec/awesome-electron-hacking

Add the awesome-electronjs-security related list

---

readme.md

Hey 
just fixing the link link for Cleavr after rebranding.
Cheers!

Update Cleavr link

---

readme.md

Project Name: Graviton Editor
Project Repository: https://github.com/Graviton-Code-Editor/Graviton-App
It's a cross-platform and modern-looking code editor. I think it should be included because a lot of people use it and I think it's awesome!
Thank you! 😄 👍🏻

Add Graviton Editor

---

readme.md

Update dead link with correct one.

Update Hawkpass link

---

readme.md

The app is a 'closed source' and built with using VueJS (https://www.coloban.com) and Quasar (https://github.com/quasarframework/quasar-awesome#projects-using-quasar).
The Desktop (Electron based) version in available at https://www.coloban.com/download (MacOS and Windows)
Many thanks!

Add Coloban

---

readme.md

Remove dead link to article

---

readme.md

The app is "closed source" and built with React.js. It is already available at Electron's registry: [https://www.electronjs.org/apps/dynobase](https://www.electronjs.org/apps/dynobase)
Dynobase is available for download [here](https://dynobase.dev). Works on MacOS, Linux and Windows.

Add Dynobase

---

readme.md

Discord re-branded with a new URL and description recently.

Update Discord URL and description

---

readme.md

Adding UpdateRocks! in the tools section.
https://www.update.rocks/

Add UpdateRocks!

---

readme.md

Looks like the author deleted TimoFM.

Remove TimoFM

---

readme.md

Hi, I am the creator of https://github.com/lostdesign/linked - it's built for macOS, Windows, and Linux see https://github.com/lostdesign/linked/releases/latest. Thanks for your time.

Add linked

---

readme.md

Hi Sindre!
Thanks for putting together such an awesome list! I am the creator of Pluggable Electron. It is a framework for building Electron apps that can be extended by other parties through plugins. See https://github.com/dutchigor/pluggable-electron.
Thanks for your consideration!

Add Pluggable Electron

---

readme.md

Hello Sindre,
Consider adding [Sigma File Manager](https://github.com/aleksey-hoffman/sigma-file-manager) to the app list.
It's a free, open-source, quickly evolving, modern file manager (explorer / finder) app for Windows and Linux.

Add Sigma File Manager to app list

---

readme.md

Add electron-vite

---

readme.md

[Aptabase](https://github.com/aptabase/aptabase) is an open source & privacy-friendly analytics platform for desktop and mobile apps.
The Electron SDK and its documentation are also on GitHub: [aptabase/aptabase-electron](https://github.com/aptabase/aptabase-electron)
Thanks for your consideration!

Add Aptabase

---

readme.md

[OpenSFTP](https://opensftp.com/) is a Beautiful integrated SSH & SFTP workspace client. 
https://opensftp.com/

Add OpenSFTP
