sindresorhus/awesome-electron

readme.md

Microsoft announced it yesterday at their Build event. They mention towards the bottom of this page that it's built with electron: https://code.visualstudio.com/Docs

Add Visual Studio Code to list of apps written

---

readme.md

Thanks for this resource! Perhaps "Components" isn't the best section, but I didn't think any of the others were a better fit.

Adds electron-cookies to list of components

---

readme.md

Linux support was added in 3.2.0. Windows support was added in 3.4.0.

electron-packager works on Linux & Windows as of last week

---

readme.md

Spark Dev is now rebranded as Particle Dev.
Blog post from May 13, 2015: http://blog.particle.io/2015/05/13/spark-is-now-particle/

Change info for Spark Dev to Particle Dev

---

readme.md

This PR adds `electron-window` to the `components` section.

Update readme.md: add electron-window

---

readme.md

It's a menubar app for listing upcoming events and recently updated repos from http://webuild.sg/
https://github.com/webuildsg/osx

Add We Build SG

---

readme.md

Link to the package: [google-music-electron](https://github.com/twolfson/google-music-electron).
This package is currently maintained and will be of use to some of the lovers of Google music.

Add unofficial Google music app

---

readme.md

https://github.com/officert/mongotron
Mongotron is an open-source Mongo DB database management tool. I built it after being frustrated with the current set of MongoDB management tools available. The project is still in its infancy, though it's becoming a very robust tool. I'd like it to be included in this list because it's an open-source project built on Electron, and I believe it to be a good example of the kinds of things that can be built using Electron.

Add a Mongotron link to open source projects.

---

readme.md

Adding Chrome DevTools App, the Chrome Inspector packaged as an app.

Add Chrome DevTools App

---

readme.md

electron-window-state is a small library to save and restore sizes and positions of Electron windows.
https://github.com/mawie81/electron-window-state

Add electron-window-state

---

readme.md

This adds a section for podcasts with a list of known episodes featuring Electron. I'm always searching for new podcasts talking about Electron, so it would be great if the community could just periodically check back here instead. :+1:

Add podcasts section with list of known episodes

---

readme.md

These repositories have already been moved to electron-userland.
* electron-prebuilt
* electron-builder

Move to electron-userland

---

readme.md

These repositories have already been moved to github.com/electron.
- electron-rebuild
- electron-compile
- spectron

Move to github.com/electron

---

readme.md

https://github.com/danhp/electron-osx-appearance
I think it's time I add this guy to the list since we've been using of it in Caprine for little while now.

Add osx-appearance

---

readme.md

Project was move from https://github.com/PalmerAL/Min to https://github.com/minbrowser/min

Update Min URL

---

readme.md

Useful tool for installing DevTools extensions directly from the Chrome WebStore

Add electron-devtools-installer

---

readme.md

iStats (display cpu and memory info on your Mac menubar)

Add iStats

---

readme.md

This is a very simple logging module for Electron application. It has no dependencies and can be used without configuration. By default it writes log files to the same folder which is used by electron (except for osx):
* **on Linux:** `~/.config/<app name>/log.log`
* **on OS X:** `~/Library/Logs/<app name>/log.log`
* **on Windows:** `$HOME/AppData/Roaming/<app name>/log.log`

Add electron-log

---

readme.md

[The old link to KeeWeb](https://github.com/antelle/keeweb) indicates the project has moved to [keeweb/keeweb](https://github.com/keeweb/keeweb). We should point there directly instead of to the "dead" repository.

Fix link to KeeWeb

---

readme.md

Support for SCSS/Sass seems to have been dropped

electron-compile: correct list of compilers

---

readme.md

Turns out the old video and the new one were both in the list. So where my previous pull replaced the deprecated video this one removes the duplicate and moves the other "quick start" video to the top of the list.

Remove duplicate link

---

readme.md

https://github.com/hardchor/electron-redux provides a way to synchronise state across windows and handle actions on both main- and renderer processes.
The issue of using redux in Electron has come up several times, e.g. in https://github.com/chentsulin/electron-react-boilerplate/issues/108#issuecomment-239665178

Add electron-redux

---

readme.md

Extraterm is an open source terminal with some unique features. It runs on Windows, macOS and Linux.

Add Extraterm

---

readme.md

I created [electron-about-window](https://github.com/rhysd/electron-about-window) to provide one-stop 'About This App' window. I introduced it on some applications and it works well cross platform 😄

Add electron-about-window

---

readme.md

This Pull Request adds a link to [Brightwheel](https://github.com/loranallensmith/brightwheel) (https://github.com/loranallensmith/brightwheel), a library that lets you build and manage Photon UI components with JavaScript.
It's similar to [React PhotonKit](https://github.com/react-photonkit/react-photonkit), but it relies on [Etch](https://github.com/atom/etch) for component management instead.

Add Brightwheel to Components section

---

readme.md

This PR adds [electron-pdf-window](https://github.com/gerhardberger/electron-pdf-window) to the tools for Electron list.
This module let's you simply add PDF viewing support to browser windows with [pdf.js](https://github.com/mozilla/pdf.js).

Add electron-pdf-window to Tools

---

readme.md

Added PB for Desktop, the open source Pushbullet desktop client app.
Reason: It should be included as its somewhat mature, already has a small user base and would benefit from additional contributors.
Link: https://github.com/sidneys/pb-for-desktop

Add PB for Desktop

---

readme.md

Router component handling communication between any number of processes in electron. Bind events in any direction, from renderer to main process  and viceversa with wildcards and duplex communication, tidying ipc.

Add electron-router

---

readme.md

This PR updates `elemon` link in readme. I changed my username from `mawni` to `manidlou`, So I updated the `elemon` link to the new repo.
- old repo: https://github.com/mawni/elemon
- new repo: https://github.com/manidlou/elemon
Sorry for inconvenience. Thanks a lot.

Update elemon link

---

readme.md

Added Desktop Dimmer, an open-source approach for controlling desktop brightness.
Reason:
It's been out there for a while ('soft-launched') and has so far proven to be of assistance to its small developer-heavy user base. Additional exposure would improve roadmaps' feature prioritization.
Link:
https://github.com/sidneys/desktop-dimmer

Add Desktop Dimmer

---

readme.md

Hi, we asked you to list our app (Sync) in this repository before. But now Sync is renamed Wantedly Chat.
You can download from https://www.wantedly.com/chat
Cc. @luvtechno 
Past pull request. https://github.com/sindresorhus/awesome-electron/pull/135
> Additions should be added to the bottom of the relevant section
If we have to add to the bottom, I'll fix it.

Rename `Sync` to `Wantedly Chat`

---

readme.md

[electron-settings](https://github.com/nathanbuchar/electron-settings) is a simple persistent user settings manager, originally adapted from Atom's own internal configuration manager. It was also just recently adopted as the settings manager of choice for Github's [demo Electron app](https://github.com/electron/electron-api-demos).

Add electron-settings to Tools

---

readme.md

I gave a talk a few weeks ago about automatically building and publishing Node.JS and Electron applications for Linux using Snapcraft. Of particular interest to Electron developers is that `electron-builder` has first class support for snaps and publishing in the snap store gives feature parity with the built-in auto-update features available in Electron for Windows and macOS. Snaps of Electron applications published in the store will be discoverable via the Software store installed by default in all major Linux distributions.
This pull request adds the video of that talk.
**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize …

Add a video: Automatically Build and Publish Node and Electron Applications for Linux

---

readme.md

I Added an entry to the Articles section that points to andea.info blog post tutorial on building desktop applications with electron

Add article

---

readme.md

I created a video course that walks you through creating and deploying an Electron app from start to finish. 
Egghead requires you to have a subscription to view all of the videos, but Egghead also allows non-subscribers to view at least a few of the videos. So I wasn't sure on whether to add that little dollar sign. I can add that in if desired. 
The course is here:
https://egghead.io/courses/build-a-desktop-application-with-electron

Add Egghead course

---

readme.md

allows for action dispatching (flux) between main & renderer processes
[ipc-flux](https://github.com/harryparkdotio/ipc-flux)
> P.S.&nbsp;&nbsp;Sorry for the new pull request, I wasn't able to edit the old one

Add `ipc-flux`

---

readme.md

Black Screen has changed its name to Upterm

Rename `Black Screen` to `Upterm`

---

readme.md

https://github.com/protonmail-desktop/application is an unofficial ProtonMail wrapper with support for multiple accounts in one window. We're planning to add more features later on. Feature proposals and feedback are welcome. 

Add unofficial ProtonMail Desktop app

---

readme.md

- This PR will be adding the [Frontend Masters Course](https://frontendmasters.com/courses/electron/) to the video section of the readme. Frontend Masters requires a paid subscription to view the video. 
I think this is a great resource people learning electron should look into. 

Add frontend master's course to the video section

---

readme.md

Buttercup (Desktop) is an open source password manager built on Electron. It's been in the wild for almost 2 years now, available on Mac, Linux and Windows.
Website: [buttercup.pw](https://buttercup.pw)

Add Buttercup Desktop

---

contributing.md
readme.md

Updated links to the old domain electron.atom.io to https://electronjs.org.

Update electron.atom.io -> electronjs.org

---

readme.md

This is [Fenêtre](https://fenêt.re), trying to improve multitasking on the Mac by letting you have a picture in picture mode for any URL or file, being a picture, a video or a flat file.
Meaning that you can have any url, picture or video in a floating window that will stay in front of everything else at all time.
I wrote a 5 articles series about its conception and publishing on the AppStore.
[Here's the first one](https://hackernoon.com/electron-on-the-appstore-pain-tears-i-early-stages-7dcb85936f92), others are linked from there.
As a plus, here's my favorite feature.
**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize …

Add Fenêtre to the list of closed source apps

---

readme.md

Headset is MIT licensed and can be built from source https://github.com/headsetapp/headset-electron

Move Headset to open source apps

---

readme.md

This PR will add **MarkText** to the list of Electron apps.
**Links**
Repo: https://github.com/marktext/marktext
Website: https://marktext.github.io/website/
Mark Text is a Markdown editor for Mac, It is a concise text editor, dedicated to improving your editing efficiency, enabling you to enjoy pleasure when you finish documents, novels and conference notes easily.
**Features**
- Realtime preview and use snabbdom as it's render engine.
- Support CommonMark Spec and GitHub Flavored Markdown Spec.
- Support paragraphs and inline style shortcuts to improve your writing efficiency.
- Output HTML and PDF file.
- Multiple themes.
- Various edit mode: Source Code mode、Typewriter mode、Focus mode.
**Source Code Mode**
**Focus Mode**
---
This change is [<img …

Add Mark Text

---

readme.md

Added Pomotroid, a simple and configurable Pomodoro timer to the 'Other' section. Pomotroid is open-source and has builds for Windows, Mac OS, and Debian/Ubuntu flavored Linux.

Add Pomotroid

---

readme.md

Removed [Kart](https://github.com/maddox/kart) as it's github says the project is defunct and abandoned.

Remove Kart

---

readme.md

According to [What's my DNS](https://www.whatsmydns.net/#A/electron.rocks), the domain name isn't resolved anymore.
**By submitting this pull request, I promise I have read the [contributing guidelines](https://github.com/sindresorhus/awesome-electron/blob/master/contributing.md) twice and ensured my submission follows it. I realize not doing so wastes the maintainers' time that they could have spent making the world better.**

Remove Electron Rocks!

---

readme.md

`ngx-electron` is an Angular module which is used to call into Electron APIs from Angular.

Add ngx-electron

---

readme.md

"Backer Timetracker" has changed the name to "Tockler" and moved the repo.

Rename `Backer Timetracker` to `Tockler`

---

readme.md

Add [electron-chrome-extension](https://github.com/getstation/electron-chrome-extension).
_electron-chrome-extension_ adds support for Chrome Extensions in Electron applications :)
----

Add electron-chrome-extension

---

readme.md

trilogy is a strongly typed layer for SQLite databases. It's especially great for Electron because it supports a pure JavaScript driver for SQLite ([sql.js](https://github.com/kripken/sql.js)) as well as the native C++ driver ([sqlite3](https://github.com/mapbox/sqlite3)). This means you can still use SQLite without the cross-platform compilation issues that can arise with `gyp` and other build tools, but switch at any time (eg. for performance benefits). …

Add trilogy

---

readme.md

[Gmail Desktop](https://github.com/timche/gmail-desktop) brings Gmail to the desktop while keeping its original interface but with a more native experience. Additionally it offers [appearance customizations](https://github.com/timche/gmail-desktop#appearance-customizations), desktop notifications, unread badges and more. This project has been inspired by Caprine to create a simple but yet powerful desktop app which the browser counterpart can't provide.

Add Gmail Desktop

---

readme.md

[electron-adblocker](https://github.com/cliqz-oss/adblocker/tree/master/packages/adblocker-electron) is a battle-tested, efficient and flexible library allowing to block ads and trackers in any Electron app. It is very easy to get started but also allows advanced customization. Written in pure TypeScript, it does not require any compilation step during installation. Last but not least, there is currently no other library in the Electron ecosystem which allows to perform both …

Add adblocker-electron

---

readme.md

The electron-create-menu package replaces the Electron menu API with one that makes it easy to create specific menus for each platform and translate them, as well as providing solid defaults for each platform.

Add electron-create-menu

---

readme.md

The owner of **electron-sandbox-boilerplate** (who is listed on the readme) [is suggesting](https://github.com/kewde/electron-sandbox-boilerplate/issues/14#issuecomment-579554998) to have people use [my template](https://github.com/reZach/secure-electron-template) over his, as his template is a bit outdated. To this end, I've updated the readme to point to [`secure-electron-template`](https://github.com/reZach/secure-electron-template).
This project is [older than 30 …

Updating secure boilerplate with new template

---

readme.md

Hi Sindre!
It looks like the [Inboxer](https://github.com/denysdovhan/inboxer) project has been deprecated and archived. I think it should be removed from the list because it is no longer maintained.

Remove Inboxer

---

readme.md

We published the code of Mouseless & Glyphfinder. This PR moves both apps to the Open Source list and changes the link to the GitHub repo.
Thanks! ✌️

Move Mouseless & Glyphfinder to Open Source section

---

readme.md

Hey,
fixing a link to the podcast on changelog here:
[old](https://changelog.com/216/) vs. [new](https://changelog.com/podcast/216/) 
Cheers!

Fix podcast link

---

readme.md

Heroic Games Launcher is a GPL3 app made with Electron for Linux, Windows and Mac as an alternative to the official Epic Games Launcher.

Add Heroic Games Launcher

---

readme.md

https://github.com/will-stone/browserosaurus
Hi Sindre 👋 
Browserosaurus is an open-source browser prompter for macOS. It works by setting itself as the default browser; any clicked links in non-browser apps are now sent to Browserosaurus where you are presented with a menu of all your installed browsers. You may now decide which app you’d like to continue opening the link with.
Browserosaurus has been a side-project of mine for over 4 years now. It's been great fun developing the UX over all that time, and learning (and coping with) all the nuances that come with Electron. But I'm pleased I could use my JS skills to create an app that I (and many others) use many times everyday.
It's currently up 737 stars. I'd be proud to see my little app on the Awesome list 🙂 
Thanks,
Will.

Add Browserosaurus

---

readme.md

Ostara is a split Electron/Spring Boot app intended to be used as a visual management tool for other Spring apps.
Link to repo: https://github.com/krud-dev/ostara
Documentation site: https://docs.ostara.dev/

Add Ostara app

---

readme.md

Conveyor is a local CLI tool that creates self-updating packages for every OS from any OS (i.e. it can cross-build and cross-sign packages without CI). It is differentiated from existing tools because it:
1. Can produce fully signed/notarized and self-updating packages for Win/Mac/Linux from any of those operating systems, including Linux CI. It can do this because it doesn't rely on Electron Forge/Builder, nor any native tooling.
2. Getting auto updates doesn't require code changes.
3. It uses Sparkle and MSIX for updates on macOS and Windows, without relying on Squirrel. This makes it easier to deploy to Windows networks.
4. It supports forced update-on-start along with various other nice features.
It's free for open source projects and doesn't rely on any services or SaaS. You can …

Add a link to Conveyor, a packaging and deployment tool

---

readme.md

Hello maintainers.
Shadowsocks is a fast tunnel proxy that helps users bypass firewalls and shadowsocks-electron provides a GUI client for easy to use it. I developed and tested it on multi operating systems especially Ubuntu which users always fall into complicated proxy configaration.

Add shadowsocks-electron

---

readme.md

Website: [www.pikatorrent.com](https://www.pikatorrent.com)
Github: [github.com/G-Ray/pikatorrent](https://github.com/G-Ray/pikatorrent)
A BitTorrent app available on desktop (electron), mobile, & even as a cli on `npm`.

Add PikaTorrent
